apiVersion: v1
kind: Namespace
metadata:
  name: flink

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  namespace: flink

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: flink
  namespace: flink

---
apiVersion: v1
kind: Namespace
metadata:
   name: flink
---
apiVersion: v1
kind: Namespace
metadata:
   name: spark
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-conf
  namespace: flink
data:
  flink-conf.yaml: |
    s3.access-key: xxxxxx
    s3.secret-key: xxxxxx
    s3.endpoint: http://s3
    s3.path.style.access: true

---
apiVersion: batch/v1
kind: Job
metadata:
  name: boot-flink
  namespace: flink
spec:
  template:
    spec:
      serviceAccount: flink
      restartPolicy: OnFailure
      containers:
      - name: start
        image: apache/flink:1.13.1-scala_2.12
        workingDir: /opt/flink
        command: ["bash", "-c", 
          "mkdir -p /opt/flink/plugins/s3-fs-hadoop && \
          cp /opt/flink/opt/flink-s3-fs*.jar /opt/flink/plugins/s3-fs-hadoop/ && \
          $FLINK_HOME/bin/kubernetes-session.sh \
          -Dkubernetes.cluster-id=flink-test \
          -Dkubernetes.jobmanager.service-account=flink \
          -Dtaskmanager.memory.process.size=1024m \
          -Dkubernetes.taskmanager.cpu=1 \
          -Dtaskmanager.numberOfTaskSlots=1 \
          -Dkubernetes.container.image=apache/flink:1.13.1-scala_2.12 \
          -Dkubernetes.namespace=flink \
          -Dhigh-availability: zookeeper \
          -Dhigh-availability.zookeeper.quorum: zookeeper:2181 \
          -Dhigh-availability.zookeeper.path.root: /flink \
          -Dhigh-availability.cluster-id: /cluster_one \
          -Dhigh-availability.storageDir: s3://flink/recovery"]
        volumeMounts:
          - mountPath: /opt/flink/conf/flink-conf.yaml
            name: flink-conf
            subPath: flink-conf.yaml
      volumes:
        - name: flink-conf
          configMap:
            name: flink-conf